# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(help_text='Enter your Question', max_length=500, verbose_name='Question ')),
                ('pub_date', models.DateTimeField(auto_now_add=True, help_text='Date Published')),
            ],
        ),
    ]
